# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0002_auto_20191109_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default='DEFAULT VALUE', max_length=60),
        ),
    ]
