# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0003_image_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
